key: "keys/backup.key"
s3:
  url: "https://127.0.0.1"
  port: 9000
  accesskey: "myaccesskey"
  secretkey: "mysecretkey"
  bucket: "dumps"
  #chunksize: 32
  cacert: "./certs/ca.pem"
elastic:
  user: "elastic"
  password: "elastic"
vault:
  addr: "http://localhost:8282"
  token: "s.7rQlPx4SI1Ke82wZBEPXeDLu"
  transitpath: "transit"
  key: "transit"