key: "keys/backup.key"
s3:
  url: "https://127.0.0.1"
  port: 9000
  accesskey: "myaccesskey"
  secretkey: "mysecretkey"
  bucket: "dumps"
  #chunksize: 32
  cacert: "./certs/ca.pem"
elastic:
  user: "elastic"
  password: "elastic"
  verifypeer: false
  cacert: ""
  clientcert: ""
  clientkey: ""
db:
  host: "localhost"
  user: "postgres"
  password: "postgres"
  database: "test"
log:
  level: debug
