s3:
  url: "https://localhost"
  port: 9000
  accesskey: "myaccesskey"
  secretkey: "mysecretkey!0"
  bucket: "dumps"
  #chunksize: 32
  cacert: "./certs/s3.pem"
elastic:
  #addr: "http://localhost:9200"
  addr: "http://localhost:9201"
  user: "elastic"
  password: "elastic"
  #index: "my-test-index"
  index: "my-test-index-mon-jan-6-11-26-58"
vault:
  addr: "http://localhost:8282"
  token: "s.lepNY18TQPM1QRZR9kW1DAhS"
  transitpath: "transit"
  key: "transit"