s3:
  url: "https://localhost"
  port: 9000
  accesskey: "myaccesskey"
  secretkey: "mysecretkey"
  bucket: "dumps"
  #chunksize: 32
  cacert: "./certs/ca.pem"
elastic:
  ## INSTANCE 1
  addr: "http://localhost:9201"
  ## INSTANCE 2
  #addr: "http://localhost:9201"
  user: "elastic"
  password: "elastic"
vault:
  addr: "http://localhost:8282"
  token: "s.S3A11UpB3LYPvKQCcMsWouRL"
  transitpath: "transit"
  key: "transit"