crypt4ghPublicKey: "./dev_tools/keys/backup.pub.pem"
crypt4ghPrivateKey: "./dev_tools/keys/backup.sec.pem"
crypt4ghPassphrase: "randomPass"
loglevel: debug
s3:
  url: "https://127.0.0.1"
  port: 9000
  accesskey: "myaccesskey"
  secretkey: "mysecretkey"
  bucket: "dumps"
  cacert: "./dev_tools/certs/ca.pem"
elastic:
  host: "http://127.0.0.1"
  port: 9200
  user: "elastic"
  password: "elastic"
  cacert: ""
