encryptionKey: "./dev_tools/keys/backup.key"
loglevel: debug
s3:
  url: "https://127.0.0.1"
  port: 9000
  accesskey: "myaccesskey"
  secretkey: "mysecretkey"
  bucket: "dumps"
  cacert: "./dev_tools/certs/ca.pem"
elastic:
  host: "http://127.0.0.1"
  port: 9200
  user: "elastic"
  password: "elastic"
  cacert: ""
db:
  host: "127.0.0.1"
  user: "postgres"
  password: "postgres"
  database: "test"
  cacert: "./dev_tools/certs/ca.pem"
  sslmode: "allow"
mongo:
  host: "127.0.0.1:27017"
  user: "backup"
  password: "backup"
  authSource: "admin"
  replicaset: ""
  cacert: "./dev_tools/certs/ca.pem"
  clientcert: "./dev_tools/certs/server.pem"
  tls: true
