crypt4ghPublicKey: "/conf/keys/backup.pub.pem"
crypt4ghPrivateKey: "./dev_tools/keys/backup.sec.pem"
crypt4ghPassphrase: ""
loglevel: debug
s3:
  url: "https://s3"
  port: 9000
  accesskey: "myaccesskey"
  secretkey: "mysecretkey"
  bucket: "dumps"
  cacert: "/conf/certs/ca.pem"
mongo:
  host: "mongodb-0:27017,mongodb-1:27017"
  user: "backup"
  password: "backup"
  authSource: "admin"
  replicaSet: "rs0"
  cacert: "/conf/certs/ca.pem"
  clientcert: "/conf/certs/server.pem"
  tls: true
