name: Code tests

on:
  push:
env:
  go-version: '1.24'

jobs:
  test:
    permissions:
      contents: read
    name: Test sensitive-data-archive
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ env.go-version }}
        uses: actions/setup-go@v5
        with:
            go-version: ${{ env.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
            go get -v -t -d .
      - name: Test
        run: go test -v -coverprofile=coverage.txt -covermode=atomic *.go

      # - name: Codecov
      #   uses: codecov/codecov-action@v5.3.1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./coverage.txt
      #     flags: unittests
      #     fail_ci_if_error: false