name: Integration test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        test: [db_test, es_test, mongo_test, db_integrity_test]

    runs-on: ubuntu-latest

    steps:

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.6'

    - name: Check out
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: install s3cmd
      run: pip3 install s3cmd

    - name: create certificates
      run: bash ./dev_tools/scripts/make_certs.sh

    - name: Start virtual infrastructure
      run: docker-compose -f ./dev_tools/docker-compose.yml up -d --force-recreate --build

    - name: Wait for containers to start
      run: bash ./dev_tools/scripts/readiness.sh

    - name: Run test
      run: bash ./dev_tools/scripts/${{ matrix.test }}.sh
